---
areaConfigurations:
- areaCode: "au"
  csvConfiguration:
    electoralListIds:
    - "AU001"
    - "AU002"
    - "AU003"
    - "AU004"
    - "AU002+AU004"
    - "AU005"
    - "AU006"
    - "AU007"
  elections:
    national:
      dates:
        44: "2001-11-10"
        45: "2004-10-09"
        46: "2007-11-24"
        47: "2010-08-21"
        48: "2013-09-07"
        49: "2016-07-02"
        50: "2019-05-18"
        51: "2022-05-21"
        52: "≤2025-09-27"
  translations:
    de: "Australien"
    en: "Australia"
    eo: "Aŭstralio"
    fr: "Australie"
    nl: "Australië"
    no: "Australia"
- areaCode: "fm"
  elections:
    national:
      dates:
        12: "2001-03-06"
        13: "2003-03-04"
        14: "2005-03-08"
        15: "2007-03-06"
        16: "2009-03-03"
        17: "2011-03-08"
        18: "2013-03-05"
        19: "2015-03-03"
        20: "2017-03-07"
        21: "2019-03-05"
        22: "2021-03-02"
        23: "2023-03-07"
        24: "2025-03-04"
  translations:
    de: "Mikronesien"
    en: "Micronesia"
    eo: "Mikronezio"
    fr: "Micronésie"
    nl: "Micronesië"
    no: "Mikronesia"
- areaCode: "mh"
  elections:
    national:
      dates:
        9: "2003-11-17"
        10: "2007-11-19"
        11: "2011-11-21"
        12: "2015-11-16"
        13: "2019-11-18"
        14: "2023-11-20"
  translations:
    de: "Marshallinseln"
    en: "Marshall Islands"
    eo: "Marŝala Insularo"
    fr: "Îles Marshall"
    nl: "Marshalleilanden"
    no: "Marshalløyene"
- areaCode: "nz"
  csvConfiguration:
    electoralListIds:
    - "NZ001"
    - "NZ002"
    - "NZ003"
    - "NZ004"
    - "NZ005"
    - "NZ006"
    - "NZ007"
    - "NZ008"
    - "NZ009"
    - "NZ010"
    - "NZ011"
    - "NZ012"
    - "NZ013"
    - "NZ014"
    - "NZ015"
    - "NZ016"
    - "NZ014+NZ016"
    - "NZ017"
    - "NZ018"
    - "NZ019"
    - "NZ020"
    - "NZ021"
  elections:
    national:
      dates:
        47: "2002-07-27"
        48: "2005-09-17"
        49: "2008-11-08"
        50: "2011-11-26"
        51: "2014-09-20"
        52: "2017-09-23"
        53: "2020-10-17"
        54: "2023-10-14"
  translations:
    de: "Neuseeland"
    en: "New Zealand"
    eo: "Nov-Zelando"
    fr: "Nouvelle-Zélande"
    nl: "Nieuw-Zeeland"
    no: "New Zealand"
- areaCode: "tv"
  elections:
    national:
      dates:
        11: "2002-07-25"
        12: "2006-08-03"
        13: "2010-09-16"
        14: "2015-03-31"
        15: "2019-09-09"
        16: "2024-01-26"
  translations:
    de: "Tuvalu"
    en: "Tuvalu"
    eo: "Tuvalo"
    fr: "Tuvalu"
    nl: "Tuvalu"
    no: "Tuvalu"
- areaCode: "vu"
  elections:
    national:
      dates:
        11: "2002-05-02"
        12: "2004-07-06"
        13: "2008-09-02"
        14: "2012-10-31"
        15: "2016-01-22"
#        16: "2020-03-19/2020-03-20"
        16: "2020-03-20"
        17: "2022-10-13"
        18: "2025-01-16"
  translations:
    de: "Vanuatu"
    en: "Vanuatu"
    eo: "Vanuatuo"
    fr: "Vanuatu"
    nl: "Vanuatu"
    no: "Vanuatu"
widgetsConfiguration:
  tableFontFamily: "Alegreya Sans,'Helvetica Neue',Helvetica,sans-serif"
  tableStylesheets:
  - https://fonts.googleapis.com/css?family=Alegreya+Sans%3A400%2C700%2C400italic%2C700italic%2C600%2C600italic%7CAlegreya+Sans%3A400%2C500%2C600%2C700%2C400italic%2C700italic&ver=1
  - https://europeelects.eu/wp-content/themes/chaplin/style.css?ver=2.6.7
